### ISSUE TITLE
直接跑起来会报错，这是为什么呢

### ISSUE THREAD

**Issue by xiecookie** [ReZeroS/weibo-prize#1]

**Comment by xiecookie** [comment]
raceback (most recent call last):
  File "E:/dolo/weibo-prize-master/weibo-prize-master/weibo.py", line 118, in <module>
    mids = get_weibo_list()
  File "E:/dolo/weibo-prize-master/weibo-prize-master/weibo.py", line 92, in get_weibo_list
    mid = cards[i]["mblog"]["mid"]
IndexError: list index out of range

**Comment by ReZeroS** [comment]
可能是没有获取到吧，没法直接跑的，因为需要确定你打算转发哪个博主的微博，大体功能就是：
首先获取博主的前几条微博（这需要你去找博主的对应信息id，就是开头几行星星号那），然后登陆微博将前几条（就是 0,3 指前三条）转发

很抱歉真的很忙最近，没时间改这个，老哥你自己多看看，主要就是把代码里星号的部分去对应上就行，找个写爬虫的肯定一看就懂

**Comment by ReZeroS** [comment]
我稍微改了下，你填上用户名密码直接跑跑看，重新看下readme

**Comment by xiecookie** [comment]
感谢兄弟，给你一个永久star hhhhhhh，我之前已经用java复写了一遍，消除了相关问题。还是非常感谢你了

**Comment by ReZeroS** [comment]
2333，永久的star可还行，多谢老哥，能帮上就好
